// Generated by CoffeeScript 1.7.1
(function() {
  var databases, mongoose;

  mongoose = require('mongoose');

  module.exports = databases = {
    connections: {},
    get: function(name) {
      return this.connections[name];
    },
    exists: function(name) {
      return this.connections[name] != null;
    },
    create: function(name, settings) {
      if (name == null) {
        throw new Error("Connection name must be provided");
      }
      if (settings == null) {
        throw new Error("Connection settings must be provided");
      }
      if (!settings.url) {
        throw new Error("Connection url must be provided");
      }
      if (settings.useDefault) {
        this.connections[name] = mongoose.connection;
      } else {
        this.connections[name] = mongoose.createConnection();
      }
      this.connections[name].settings = settings;
      return this.connections[name];
    },
    connect: function(cb) {
      var all, connectTo, connected, connection, name, _ref, _results;
      all = function(hash) {
        var name, value;
        for (name in hash) {
          value = hash[name];
          if (!value) {
            return false;
          }
        }
        return true;
      };
      connectTo = (function(_this) {
        return function(name, settings, callback) {
          var finishOrRetry, options, url;
          url = settings.url;
          options = settings.options;
          finishOrRetry = function(err, result) {
            var _ref;
            if (err != null) {
              if ((_ref = settings.logger) != null) {
                _ref.error(err, "Failed to connect to `" + url + "` on startup - retrying in 5 sec");
              }
              return setTimeout((function() {
                return connectTo(name, settings, callback);
              }), 5000);
            } else {
              connected[name] = true;
              if (all(connected)) {
                return typeof cb === "function" ? cb() : void 0;
              }
            }
          };
          if (url.indexOf(',') >= 0) {
            return _this.connections[name].openSet(url, options, finishOrRetry);
          } else {
            return _this.connections[name].open(url, options, finishOrRetry);
          }
        };
      })(this);
      connected = {};
      _ref = this.connections;
      _results = [];
      for (name in _ref) {
        connection = _ref[name];
        if (connection.readyState === 0) {
          connected[name] = false;
          _results.push(connectTo(name, connection.settings));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    },
    disconnect: function(callback) {
      return mongoose.disconnect(callback);
    }
  };

}).call(this);
